services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ~/data/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.digi-a.org`)"
    networks:
        - proxy
networks:
  proxy:
    external: true
