services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: all
      FTLCONF_misc_privacylevel: 0
    volumes:
      - ~/data/pi-hole/etc-pihole:/etc/pihole
      - ~/data/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.digi-a.org`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.middlewares=pihole-admin-redirect"
      - "traefik.http.middlewares.pihole-admin-redirect.redirectregex.regex=^https://pihole\\.local\\.digi-a\\.org/?$$"
      - "traefik.http.middlewares.pihole-admin-redirect.redirectregex.replacement=https://pihole.local.digi-a.org/admin"
      - "traefik.http.middlewares.pihole-admin-redirect.redirectregex.permanent=true"
    networks:
      - proxy
networks:
  proxy:
    external: true
